### ISSUE TITLE
`TypeError: 'NoneType' object is not subscriptable` when running `sephiroth -s nginx -t asn -a AS15169 -a AS31337 -t azure`

### ISSUE THREAD

**Issue by buvanesh-s** [0xdade/sephiroth#81]
When running the command sephiroth -s nginx -t asn -a AS15169 -a AS31337 -t azure, an error occurs during the fetching of IP ranges. The traceback indicates a TypeError in the Azure provider.

**Steps to Reproduce**
* Install sephiroth using pip.
* Run the following command:
```sh
$ sephiroth -s nginx -t asn -a AS15169 -a AS31337 -t azure
(asn) Fetching IP ranges from api.hackertarget.com for 2 ASNs
(azure) Fetching IP ranges from Microsoft
Traceback (most recent call last):
  File "/usr/local/bin/sephiroth", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/Sephiroth.py", line 237, in main
    provider, excludeip6=args.excludeip6, compacted=args.compacted
  File "/usr/local/lib/python3.6/dist-packages/Sephiroth.py", line 43, in get_ranges
    provider = Provider(selected_provider)
  File "/usr/local/lib/python3.6/dist-packages/sephiroth/providers/provider.py", line 20, in __init__
    self.provider = classmap[provider]()
  File "/usr/local/lib/python3.6/dist-packages/sephiroth/providers/azure.py", line 9, in __init__
    self.source_ranges = self._get_ranges()
  File "/usr/local/lib/python3.6/dist-packages/sephiroth/providers/azure.py", line 19, in _get_ranges
    direct_link = soup.select_one(".failoverLink")["href"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by 0xdade** [comment]
Hi there, I think this is related to #80, which I have on my backlog but was traveling when it was filed. I'll test that branch out and get it merged today if it fixes the issue!

**Comment by 0xdade** [comment]
@buvanesh-s Can you install 1.0.4 and see if your problem is gone? Works here now!

**Comment by buvanesh-s** [comment]
Thanks, it worked now.
